'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import { DataContext } from "./dataContext";
import { Goals } from "./types";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [points, setPoints] = useState<string>();
  const [goals, setGoals] = useState<Goals>();

  const getPoints = async () => {
    const res = await fetch("api/points", {
      method: "GET",
    });
    const data = await res.json();
    setPoints(data);
  };

  const getGoals = async () => {
    const res = await fetch("api/goals", {
      method: "GET",
    });
    const data = await res.json();
    setGoals(data);
  };

  useEffect(() => {
    getGoals();
  }, []);

  useEffect(() => {
    if (!points) {
      getPoints();
    }
  }, [points]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <DataContext.Provider value={{
          points: points || '',
          goals: goals || {},

        }}>
          {children}
        </DataContext.Provider>
      </body>
    </html>
  );
}
