'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import { PointsContext } from "./dataContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [points, setPoints] = useState<string>();

  const getPoints = async () => {
    const res = await fetch("api/points", {
      method: "GET",
    });
    const data = await res.json();
    setPoints(data);
  };

  if (!points) {
    getPoints();
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <PointsContext.Provider value={points || ''}>
          {children}
        </PointsContext.Provider>
      </body>
    </html>
  );
}
